security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_STUD:        ROLE_USER
        ROLE_PROF:        ROLE_USER
        ROLE_ADMIN:       [ROLE_STUD,ROLE_PROF,ROLE_USER]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                path:     /logout
                target:   /easysaisie
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/user$, role: ROLE_ADMIN }
        - { path: ^/easysaisie/formation, role: ROLE_ADMIN }
        - { path: ^/easysaisie/promotion, role: ROLE_ADMIN }
        - { path: ^/easysaisie/container, role: ROLE_ADMIN }
        - { path: ^/easysaisie/subject, role: ROLE_ADMIN }
        - { path: ^/easysaisie/teachingunit, role: ROLE_ADMIN }
        - { path: ^/easysaisie/student, role: ROLE_ADMIN }
        - { path: ^/easysaisie/rule, role: ROLE_ADMIN }
        - { path: ^/easysaisie, role: ROLE_USER }