<?php

namespace C2J\EasySaisieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContainerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContainerRepository extends EntityRepository
{
	public function getContainers($promotionId = null)
	{	
		$queryBuilder = $this->createQueryBuilder('c');
        if($promotionId != null)
        {
            $queryBuilder->andWhere('c.promotion = :promotionId')
            ->setParameter('promotionId', $promotionId);
        }
        return $queryBuilder;
	}
}
