<?php

namespace C2J\EasySaisieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarkRepository extends EntityRepository
{
	public function findAllMarksByStudentsByPromotion($id) 
	{
		return $this->createQueryBuilder('m')
					->join('m.teachingUnitSubject', 'tus')
						->addSelect('tus')
					->join('tus.subject', 'sub')
						->addSelect('sub')
					->join('tus.teachingUnit', 'tu')
						->addSelect('tu')
					->join('tu.container', 'c')
						->addSelect('c')
					->join('m.studentPromotion', 'sp')
						->addSelect('sp')
					->join('sp.student', 's')
						->addSelect('s')
					->join('sp.promotion', 'p')
						->addSelect('p')

					->where('sp.id = :id')
					->setParameter('id', $id)
					->getQuery()
					->getResult();
	}
}
