<?php

namespace C2J\EasySaisieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends EntityRepository
{
	public function findAllSubjectsByTusByContainerByPromotionByYear($promotion_id, $year) 
	{
		return $this->createQueryBuilder('p')
					->join('p.containers', 'c')
						->addSelect('c')
					->join('p.studentPromotions', 'sp')
						->addSelect('sp')
					->join('c.teachingUnits', 'tu')
						->addSelect('tu')
					->join('tu.teachingUnitSubjects', 'tus')
						->addSelect('tus')
					->where('p.id = :promotion_id')
						->setParameter('promotion_id', $promotion_id)
					->andWhere('sp.year = :year')
						->setParameter('year', $year)
					->addOrderBy('tu.code', 'ASC')
					->getQuery()
					->getResult();
	}
}
