<?php

namespace C2J\EasySaisieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StudentPromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentPromotionRepository extends EntityRepository
{
	public function findAllPromotionsByYearDistinct() 
	{
		$qb = $this ->createQueryBuilder('sp')
					->join('sp.promotion', 'p')
					->addSelect('p')
					->groupBy('p.name')
					->orderBy('sp.year', 'DESC')
					->addOrderBy('p.name', 'ASC');

	    // $qb = $this ->createQueryBuilder('sp')
	    //             ->select('p.name')
	    //             ->distinct()
	    //             ->addSelect('sp.id')
	    //             ->addSelect('sp.year')
	    //             ->join('sp.promotion', 'p')
	    //             ->orderBy('sp.year', 'DESC')
	    //             ->addOrderBy('p.name', 'ASC');

		return $qb 	->getQuery()
					->getResult();
	}
}
